# Generated by Django 5.2.8 on 2025-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.PositiveIntegerField(),
        ),
    ]
