# Generated by Django 5.2.8 on 2025-11-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_ingreso_fecha_alter_ingreso_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='costo_gasto',
            field=models.CharField(choices=[('Costo', 'Costo'), ('Gasto', 'Gasto')], default='Costo', max_length=20, verbose_name='Tipo de Egreso'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='operacional_noperacional',
            field=models.CharField(choices=[('Operacional', 'Operacional'), ('No Operacional', 'No Operacional')], default='Operacional', max_length=20, verbose_name='Tipo de Ingreso'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='costo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
