# Generated by Django 5.2.8 on 2025-11-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requiere_cambio_password',
            field=models.BooleanField(default=True),
        ),
    ]
