# Generated by Django 5.2.8 on 2025-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_profile_requiere_cambio_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='creado_por_nombre_fijo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='creado_por_nombre_fijo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='creado_por_nombre_fijo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
