# Generated by Django 6.0 on 2025-12-16 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='cliente_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.cliente', verbose_name='Seleccionar Cliente'),
        ),
    ]
