# Generated by Django 6.0 on 2025-12-17 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_ingreso_cliente_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='cliente',
        ),
        migrations.CreateModel(
            name='AuditoriaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('id_original', models.IntegerField()),
                ('accion', models.CharField(choices=[('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('detalles_anteriores', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
