# Generated by Django 6.0 on 2025-12-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_remove_ingreso_cliente_auditoriamovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
