# Generated by Django 6.0 on 2025-12-17 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_egreso_activo_ingreso_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.egreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.inventarioitem')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.inventarioitem')),
            ],
        ),
    ]
