# Generated by Django 6.0 on 2025-12-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_detalleegreso_detalleingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='numero_factura',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
