# Generated by Django 6.0 on 2025-12-17 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_egreso_numero_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=2700.0, max_digits=10, verbose_name='Valor por Hora'),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('mes_correspondiente', models.CharField(max_length=20, verbose_name='Mes/Año (Ej: Enero 2024)')),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, max_digits=5)),
                ('valor_hora_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
