# Generated by Django 6.0 on 2025-12-17 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_codigoverificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('horas_estimadas', models.DecimalField(decimal_places=1, max_digits=6)),
                ('valor_hora_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_servicio', models.TextField()),
                ('total_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cotizacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contabilidad.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.inventarioitem')),
            ],
        ),
    ]
