# Generated by Django 6.0 on 2025-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_cotizacion_itemcotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
